In [ ]:
# pip install theano

In [ ]:
# pip install tensorflow

In [ ]:
# pip install keras

#Data Preprocessing

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x=df.iloc[:,3:13].values
y=df.iloc[:,13].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Country column
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
x = ct.fit_transform(x)

# Male/Female
labelencoder_X = LabelEncoder()
x[:, 4] = labelencoder_X.fit_transform(x[:, 4])
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
print(x[0])

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [ ]:
#splitting the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
print(X_train)
print(X_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


#Building ANN

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:
X_train.shape

(8000, 12)

In [ ]:
classifier=Sequential()

In [ ]:
#input and hidden layers with dropout layer
classifier.add(Dense(units=6, activation='relu',input_dim=12))
classifier.add(Dropout(rate=0.1))

In [ ]:
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dropout(rate=0.1))

In [ ]:
classifier.add(Dense(units=1, activation='sigmoid'))

In [ ]:
#Compiling ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#Fitting ANN to training set
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4857 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4514 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4397 - accuracy: 0.7959
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4278 - accuracy: 0.8029
Epoch 5/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4176 - accuracy: 0.8174
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4057 - accuracy: 0.8185
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3962 - accuracy: 0.8215
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3926 - accuracy: 0.8344
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3842 - accuracy: 0.8416
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3848 - accura

#Making Predictions and Evaluating Model

In [ ]:
#predictions on test set
y_pred=classifier.predict(X_test)
y_pred

63/63 [==============================] - 0s 1ms/step


array([[0.231923  ],
       [0.15135863],
       [0.05976742],
       ...,
       [0.10494788],
       [0.13262019],
       [0.21185334]], dtype=float32)

In [ ]:
#setting threshold
y_pred=(y_pred>0.5)
y_pred


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
#making confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1546,   49],
       [ 221,  184]])

In [ ]:
#accuracy on the test set(on which the model was not trained)
acc=(1520+209)/2000
acc

0.8645

In [ ]:
print(X_train[0])

[-1.01460667 -0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796
  0.00666099 -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]


In [ ]:
#making prediction on a new single observation
#France(3 vals since encoded dummy variables)
#credit score=600
#gender=male
#Age=40
#Tenure=3
#balance=60000
#number of products=2
#has credit card=yes
#is active member=yes
#Estimated salary=50000
new_pred=classifier.predict(sc.transform(np.array([[1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000]])))
new_pred=(new_pred>0.5)
print(new_pred)

1/1 [==============================] - 0s 22ms/step
[[False]]


In [ ]:
#so customer is not likely to leave the bank

#Evaluating, Improving and Tuning the ANN

In [ ]:
#Evaluating the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
def build_classifier():
  classifier=Sequential()
  classifier.add(Dense(units=6, activation='relu',input_dim=12))
  classifier.add(Dense(units=6, activation='relu'))
  classifier.add(Dense(units=1, activation='sigmoid'))
  classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return classifier

classifier=KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=100)
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10,n_jobs=-1)


<ipython-input-26-eb97b1498562>:14: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier=KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=100)


In [ ]:
print(accuracies)

[0.85374999 0.84625    0.8725     0.85250002 0.87374997 0.86624998
 0.84875    0.84625    0.84875    0.87124997]


In [ ]:
mean=accuracies.mean()
variance=accuracies.std()
print(mean)
print(variance)

0.8579999923706054
0.010943026329100254


In [ ]:
#improving ANN by introducing dropout layer
#tuning ANN by trying out multiple parameters to find the best one
#---------------------------